travis:
  secure:
    BINSTAR_TOKEN: M6TzEuFmwR1rDvWYMWNJ1/cCj1MLfjGQhKOkVWZJqALjjuYAqlZ7u3c2LHNymk5Lwi02duTzxV2lQxoSrwWBr3gfrXrLTvHpaSOy1KWPGHWD+lO+1viSSjpnf5aFF6AvjBGgYlRgD6ZGcJXvExSkeBmNUIJ3jHoArlEzNbhQSsRVIXVBQFvpfofYg1yusUMwBdRdEGA0gIaKe3CV5KC1TfiY9cb9KuHc4yKN0jVzaem3ufwv7XvejPd/n0cD509CGjliQ+6XPre3JKp8izXfVHaF17qDl4zOnCjpZ4zYU5AIrrHCQs09YmCcO1lC1ss71RSV/kC+SPVYPbPuvrRn+GsKzqVPnv8OFpi3Ix4gWyVsdyxBvmC+re2On0CsUvqo3mExfzYv1mDHh/SfenSI1QT6k71gKJUK6uY8UNr8uuKn6Ns8e9bqVmQmNFHNLio7LJfHZX6eotHESvGwThvX3/51UgDeOeABaoXrfNVT+umYO/+5RARkATNXaKMvNhfW+W5snwXLI7EzuC/wbY/PlxRDmFrejrRaimvTIP64r5WhvmlVYkl1oxlogMDjbl/B17cSP7bSG4W7v5S8t1lrlzIS5tYMKqLvApT+qC56qj9WVkXF/0cTBwwxLCPXbwNUXZwogra+D3I5b1cnz/6NhphloWp5qvfWfRxk/Hi2ZdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
