travis:
  secure:
    BINSTAR_TOKEN: TArHF6q5sXoHT0d/M02A9ktdIk0lBPKse6tvbLEgBhBhbIqslk5acY6fl2WoWSwXVLrWVPl9Z3+k8iriDa+lO0fBFNx8IjnSp03Az4uPjlOB0QDoZhIT/Ugq2IRLz9P8YoQRVyMZpe0QhS5ZWnprMnou8HU1144s2kCjkGhqvUMfVQhjjsEHLtZShuR64pUcJM8PCAWzpRZi/E0afG9wHw3Lcm6+nqq6VK67WTtCBcdsslkUsae524yvAtTaTk662t+Rue3SIciE+4Z6P23aKx11qeOqx+LzDFwt2rXEV+BKmOUs0Z4B/NPMeXyv9fMeMehDWmORT+DcNNUYxWhElZERRq6yFrTJeaTrnVa7UTDcaL3PvrZaBAQQow55EYj1KJYGqOV6uM2Ebtlt183xFzlxRR8/rR3aCwaLfnnh4Fo5S0kuizPzFZPxmEL6ooVNPO0joXtkG8OTuJhfENDN757aZ8LPRvLgZPe/1cASTxqWkOR1xGPuU1SZSvDd/bGUC0pJ4BRQWqVV7zWiHi39bqpnMko1letBn+sZVFpGf7GBDf0QD8ucHKKelU3CJZsPjkRG5j9MXopmbBHsvXR07Klfhwv+RrPif29obcrIrIA5mmTjv/AbnThBSRvRxz0HfmWZrHwfGijikoaNn1aUi+L4JE6IaqTrDi+GrWupqck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
